# Generated by Django 4.2.4 on 2023-09-25 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_parent'),
        ('account', '0004_user_favorites_user_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='blog.post', verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='account/default_avatar.png', upload_to='account/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info', to='account.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='education',
            field=models.ManyToManyField(blank=True, related_name='info', to='account.university', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='work',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
    ]
